export const menu = [
    {
        id:1,
        title:"main",
        listItems:[
            {
                id:1,
                title:"HomePage",
                url:"/",
                icon:"/home.svg",
            },
            {
                id:2,
                title:"Profile",
                url:"/",
                icon:"/profile.svg",
            },
        ],
    },
    {
        id:2,
        title:"Vehicles",
        listItems:[
            {
                id:1,
                title:"Vehicles",
                url:"/",
                icon:"/truck.svg",
            },
            {
                id:2,
                title:"Installation",
                url:"/",
                icon:"/install.svg",
            },
        ],
    },
    {
        id:3,
        title:"Devices",
        listItems:[
            {
                id:1,
                title:"Devices",
                url:"/",
                icon:"/device.svg",
            },
            {
                id:2,
                title:"Devices Type",
                url:"/",
                icon:"/install.svg",
            },
            {
                id:2,
                title:"Sim Management",
                url:"/",
                icon:"/sim.svg",
            },
        ],
    },
    {
        id:4,
        title:"Troubleshoot",
        listItems:[
            {
                id:1,
                title:"troubleshoot",
                url:"/",
                icon:"/device.svg",
            },
        ],
    },
    {
        id:5,
        title:"Devices",
        listItems:[
            {
                id:1,
                title:"Devices",
                url:"/",
                icon:"/device.svg",
            },
            {
                id:2,
                title:"Devices Type",
                url:"/",
                icon:"/install.svg",
            },
            {
                id:2,
                title:"Sim Management",
                url:"/",
                icon:"/sim.svg",
            },
        ],
    },
    {
        id:6,
        title:"Devices",
        listItems:[
            {
                id:1,
                title:"Devices",
                url:"/",
                icon:"/device.svg",
            },
            {
                id:2,
                title:"Devices Type",
                url:"/",
                icon:"/install.svg",
            },
            {
                id:2,
                title:"Sim Management",
                url:"/",
                icon:"/sim.svg",
            },
        ],
    },
    {
        id:7,
        title:"Devices",
        listItems:[
            {
                id:1,
                title:"Devices",
                url:"/",
                icon:"/device.svg",
            },
            {
                id:2,
                title:"Devices Type",
                url:"/",
                icon:"/install.svg",
            },
            {
                id:2,
                title:"Sim Management",
                url:"/",
                icon:"/sim.svg",
            },
        ],
    },
    {
        id:8,
        title:"Devices",
        listItems:[
            {
                id:1,
                title:"Devices",
                url:"/",
                icon:"/device.svg",
            },
            {
                id:2,
                title:"Devices Type",
                url:"/",
                icon:"/install.svg",
            },
            {
                id:2,
                title:"Sim Management",
                url:"/",
                icon:"/sim.svg",
            },
        ],
    },
    {
        id:9,
        title:"Devices",
        listItems:[
            {
                id:1,
                title:"Devices",
                url:"/",
                icon:"/device.svg",
            },
            {
                id:2,
                title:"Devices Type",
                url:"/",
                icon:"/install.svg",
            },
            {
                id:2,
                title:"Sim Management",
                url:"/",
                icon:"/sim.svg",
            },
        ],
    },
    
]